### ISSUE TITLE
Exception : Unable to cast object

### ISSUE THREAD

**Issue by LaurentDardenne** [nohwnd/Profiler#36]
Profiler version 3.0.1 (Windows  Serveur 2012)

Exception with this code :
```Powershell
$trace =  Trace-Script -ScriptBlock { & E:\RELEASES\XYZ\WpfTools.ps1}
```
![image](https://user-images.githubusercontent.com/4894452/117164347-d42f5880-adc4-11eb-839e-ec0d5e02b53f.png)
There are other errors with PS v7.1.0 

Same error with :
```Powershell
$trace =  Trace-Script -ScriptBlock { Dir }
```

```
$PsVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.14409.1018}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by nohwnd** [comment]
#25 We have the cast issue reported here, only thing I can recommend right now is cloning this repo and trying to run the demo.ps1, the dlls are now pushed in the repo so you don't have to build.

I cannot repro it on my side, I am building on server 2016 and it passes. 

The null issue is totally my fault, trying to .trim() on possibly null object is stupid...

**Comment by nohwnd** [comment]
Null ref fixed in #38

**Comment by LaurentDardenne** [comment]
Thank you.

_>>The null issue is totally my fault, trying to .trim() on possibly null object is stupid..._
Only those who do nothing are never wrong ;-)

**Comment by nohwnd** [comment]
Did your cast problem got solved or are you moving to the other issue?

**Comment by LaurentDardenne** [comment]
I no longer have an exception using the last commit.
