### ISSUE TITLE
Top50 and Top50Duration are identical

### ISSUE THREAD

**Issue by fflaten** [nohwnd/Profiler#8]
Now that Duration is total duration and not SelfDuration then both views are identical so one of them can be removed to avoid confusion and processing

Top50 sorts on percentage of duration/totalduration while Top50Duration sorts by highest duration. AFAIK they will always return the same list.

**Comment by nohwnd** [comment]
Yup you are right. I was thinking about that as well. They were identical before as well, pretty much. Just that Percent used more rounding.
